### ISSUE TITLE
Create an "SRI-enabled CDN" section

### ISSUE THREAD

**Issue by fmarier** [mozilla/srihash.org#10]
Once we have convinced CDN vendors to include the integrity attribute on their sample code pages, we should link to them as "SRI-enabled CDNs".

**Comment by neftaly** [comment]
I'm not quite sure how to word this section. At the moment, I have something like this:

---

### SRI-supporting CDNs
Content hosts are encouraged to add the *integrity* attribute to reference HTML elements, along with a link to the original project page, asserting to the validity of the hash.

The following CDNs are known to list SRI attributes:
            
* [jQuery CDN](https://code.jquery.com)
* [Cloudflare CDNJS](https://cdnjs.com)
* etc

If you wish to add to this list, please [open an issue](https://github.com/mozilla/srihash.org/issues/new?title=Add%20CDN:%20).

---

My concern is that automatically trusting a CDN's hash is a bad practice; users should be in the habit of confirming digests beforehand. 

Is this worth worrying about? Can you think of a way to word it better?

**Comment by fmarier** [comment]
In my mind the purpose of that section is to promote the CDNs that promote this feature by including it in their code examples.

If a developer is going to blindly copy and paste some code and include JS hosted elsewhere in their app, they're not likely to go to the upstream source and verify that the hashes are the same.

I think your blurb is a good start (and I really like the "If you wish to be added to this list, file an issue" link). I would simply drop the first paragraph. In any case, we don't need to add it until we actually have one CDN that has signed up for it :)

**Comment by neftaly** [comment]
Fair enough. Can I close this issue with a commit containing a commented-out example?

**Comment by fmarier** [comment]
We can also just leave it open to remind us that we intend to reach out to CDNs and add them to our page :)

**Comment by fmarier** [comment]
@mozfreddyb pointed out to me that [BootstrapCDN](https://www.bootstrapcdn.com/) includes the `integrity` attribute in their sample HTML.

**Comment by mozfreddyb** [comment]
Yeah, kudos to @jonathanKingston! He talked to a few CDNs over the last few weeks.
Maybe there are even more, which I forgot?

**Comment by jonathanKingston** [comment]
Yup so I started a brief page of the ones I filed (only Bootstrap was easy enough to kick off a patch which they then finished for all files):
https://secure.fail/SRI.html

Let me know of any others (The whole site is designed to remind people about these things but vastly not finished - sorry :/)

**Comment by fmarier** [comment]
> Yup so I started a brief page of the ones I filed (only Bootstrap was easy enough to kick off a patch which they then finished for all files):
> https://secure.fail/SRI.html

That's awesome, thanks!

**Comment by mozfreddyb** [comment]
Yeah, thanks @jonathanKingston. I just went around and bumped all of these threads where I thought it might help :-)

**Comment by fmarier** [comment]
[jsDelivr](http://jsdelivr.com) (no HTTPS available) now also has an option for SRI, though it's disabled by default unfortunately.

**Comment by mozfreddyb** [comment]
Closing as WONTFIX, I don't think we need to advocate for certain CDNs.
