### ISSUE TITLE
Fix HTML validation errors

### ISSUE THREAD

**Issue by XhmikosR** [mozilla/srihash.org#105]
https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.srihash.org%2F

You could add [grunt-html](https://github.com/jzaefferer/grunt-html) to test locally in the future.

**Comment by mozfreddyb** [comment]
Yes, but there seems limited value in using this, as it will complain about SRI itself ;)

> `Error: Attribute integrity not allowed on element link at this point.`

**Comment by XhmikosR** [comment]
Nope, that is because you have the `link` there, in `body`.

**Comment by mozfreddyb** [comment]
Ah! :)
