### ISSUE TITLE
Add font fallbacks

### ISSUE THREAD

**Issue by XhmikosR** [mozilla/srihash.org#112]
While testing locally with IE9, I noticed some text is missing. It's normal, since you only load a woff.

So, either we use the bulletproff `@font-face syntax` or we just make sure we have fallbacks everywhere.

/CC @mozfreddyb

**Comment by mozfreddyb** [comment]
Sure, file a PR with a suggestion, I'm fine with whatever works.

**Comment by XhmikosR** [comment]
Don't close it yet, I'm not Flash :P

**Comment by XhmikosR** [comment]
Both will work. It depends what you want guys want.

The bulletproof syntax will work in all browsers but we'll need to add more font files to the repo. The fallback approach should also work without the extra files.

**Comment by mozfreddyb** [comment]
woff support seems pretty widespread according to http://caniuse.com/#feat=woff
I guess a fallback font would be enough. WDYT @fmarier?

**Comment by XhmikosR** [comment]
After looking into it, we can just ignore it. Let me make a PR.

**Comment by fmarier** [comment]
> I guess a fallback font would be enough. WDYT @fmarier?

Yeah, I don't think we should get out of our way to make it look good on obsolete browsers. I mean it should work and be readable, but it's totallly fine IMHO if it looks different.
