### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by XhmikosR** [mozilla/srihash.org#119]
Maybe we could use one of the badges, the success one?

**Comment by mozfreddyb** [comment]
I suck at design, but I can say what I find pretty and not, if you have something to show :package: Do you want to proceed with a pull request?

Alternatively, we could ask design folks at [@mozilla/Community-Design](https://github.com/mozilla/Community-Design) like @elioqoshi

**Comment by XhmikosR** [comment]
I'm not a designer myself, so that's why I suggested using https://github.com/mozilla/srihash.org/blob/master/public/badge/pass.svg :)

I can make a PR with that.

**Comment by elioqoshi** [comment]
I can help, what do you need!
