### ISSUE TITLE
Suspected erroneous hashes for CSS assets

### ISSUE THREAD

**Issue by minxomat** [mozilla/srihash.org#125]
The generator seems to fail in odd ways for certain CSS files:

- 50% of the time it throws a "unknown error"
- The rest of the time it generates a wrong hash

The relevant bug report is [Bug No. 1271796](https://bugzilla.mozilla.org/show_bug.cgi?id=1271796). If you need access to the test files, drop me your email address at squarecode@web.de, or post it here.

There are multiple issues colliding here, one of them is a suspect bug in FF's hashing routine. You might want to get a CC on that bug.

**Comment by fmarier** [comment]
@jonathanKingston Is this something you'd like to take a look at?

**Comment by fmarier** [comment]
I wonder whether some of the problems here were due to gzip encoding. If so, #142 will probably fix this.

**Comment by fmarier** [comment]
Based on https://bugzilla.mozilla.org/show_bug.cgi?id=1271796#c21, I think we can consider this fixed.
