### ISSUE TITLE
AWS S3 needs Origin header in CORS request

### ISSUE THREAD

**Issue by josephsu** [mozilla/srihash.org#149]
The current implementation does not work with resources hosted on AWS S3.

Reason: AWS S3 only sends access-control-allow-origin in the HTTP response if the original HTTP request has Origin in the header. [1]

Potential Fix: In https://github.com/mozilla/srihash.org/blob/master/lib/helpers.js#L131 it's making HTTP request to fetch resource without Origin header. We can add a Origin header there so the AWS S3 will reply with access-control-allow-origin in headers. 

Reference: [1] http://docs.aws.amazon.com/AmazonS3/latest/dev/cors-troubleshooting.html

**Comment by mozfreddyb** [comment]
Thanks for filing this, @josephsu!

Fixing this by adding the Origin header in our requests sounds plausible.
Do you have a file hosted on AWS S3 that I could use for testing?

**Comment by josephsu** [comment]
Here's the sample file on S3: http://www.plaxie.com.s3.amazonaws.com/index.html

curl request without Origin header:
```
$ curl -v http://www.plaxie.com.s3.amazonaws.com/index.html
* Hostname was NOT found in DNS cache
*   Trying 54.231.82.50...
* Connected to www.plaxie.com.s3.amazonaws.com (54.231.82.50) port 80 (#0)
> GET /index.html HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.plaxie.com.s3.amazonaws.com
> Accept: */*
>
< HTTP/1.1 200 OK
< x-amz-id-2: tMEfTV7IHUUGiscxKEv657SCdXqKTTHfLbB38ToQ7pQmICTY4yjhSrsetpVj3f0t27+oaR1YbeM=
< x-amz-request-id: 234D4373F90FE53C
< Date: Tue, 11 Oct 2016 12:47:13 GMT
< Last-Modified: Sat, 01 Dec 2012 01:28:04 GMT
< ETag: "0f3d53c1be6a28a3bfde8c728b85ca2c"
< Accept-Ranges: bytes
< Content-Type: text/html
< Content-Length: 151
* Server AmazonS3 is not blacklisted
< Server: AmazonS3
<

```
curl with Origin header:
```
$ curl -H "Origin: www.example.com" -v http://www.plaxie.com.s3.amazonaws.com/index.html
* Hostname was NOT found in DNS cache
*   Trying 54.231.82.50...
* Connected to www.plaxie.com.s3.amazonaws.com (54.231.82.50) port 80 (#0)
> GET /index.html HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.plaxie.com.s3.amazonaws.com
> Accept: */*
> Origin: www.example.com
>
< HTTP/1.1 200 OK
< x-amz-id-2: EU7zARilF1MStmFPMcnV2FdSboQiLsrSVc/SsnJQmJCsSdLMJedAHbXAQw30JgbWMu951Vo3J0U=
< x-amz-request-id: 1C18A3874BCA03AB
< Date: Tue, 11 Oct 2016 12:47:07 GMT
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET
< Access-Control-Max-Age: 3000
< Vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
< Last-Modified: Sat, 01 Dec 2012 01:28:04 GMT
< ETag: "0f3d53c1be6a28a3bfde8c728b85ca2c"
< Accept-Ranges: bytes
< Content-Type: text/html
< Content-Length: 151
* Server AmazonS3 is not blacklisted
< Server: AmazonS3
<

```

**Comment by mozfreddyb** [comment]
This file is not super useful, as it won't pass other checks in our backend. We need a script or a stylesheet.

**Comment by josephsu** [comment]
how about this one: http://www.plaxie.com.s3.amazonaws.com/jquery-3.1.1.min.js

**Comment by SamHoulder** [comment]
Hi
Could you please deploy this fix asap or inform your site visitors of the issues with S3 and the missing Origin-header. We are seeing several requests to "fix" our CORS settings at S3 for code.highcharts.com. All referring the hash-generator at the srihash.org
Thanks

**Comment by fmarier** [comment]
There is a pull request already queued up for this (https://github.com/mozilla/srihash.org/pull/150) but it fails the test suite for some reason.

We haven't yet been able to fix this Travis CI failure: https://travis-ci.org/mozilla/srihash.org/builds/308383207.

**Comment by fmarier** [comment]
Thanks to @XhmikosR for figuring out what was wrong in #150!
