### ISSUE TITLE
Incorrect hash created.

### ISSUE THREAD

**Issue by jdalton** [mozilla/srihash.org#152]
The `integrity` value of 

```
https://cdn.jsdelivr.net/g/fuse@2.5.0,immutable.js@3.8.1,react@15.3.2(react.min.js+react-dom.min.js)
```

Should be

```
sha384-NFvWg391HUzxoyYtBHIFpwz8GQwmfhqOTtkoDntpx1pGfKmWfxwcNFPrjQbEXk9L
```

But is reported as

```
sha384-Xq2FD+sjFm4/O+2juF28ku89C4+e85gUKbgx1smo/LtIkjjQmr8oClnpwMs25MOD
```

**Comment by jdalton** [comment]
If I download [the file](https://cdn.jsdelivr.net/g/fuse@2.5.0,immutable.js@3.8.1,react@15.3.2(react.min.js+react-dom.min.js)) and run commands locally it generates the correct value. I see this even when using the `sri-toolbox` package. If I retrieve the file from the cdn and process it, it produces the wrong values. If I save the same source to a file and open it and then process it, it generates the correct value. Maybe it's an encoding thing?

**Comment by jdalton** [comment]
It looks like the file when retrieved via the result of the `https.get` is missing a trailing `\n`.

**Comment by jdalton** [comment]
It looks like a bug in jsdeliver trimming the trailing `\n` for [non-gzipped/non-deflated responses](https://github.com/jsdelivr/jsdelivr/issues/14459).

**Comment by fmarier** [comment]
Thanks for flagging this. Let's follow-up on the jsdelivr bug tracker.
