### ISSUE TITLE
CORS: You're a bad example

### ISSUE THREAD

**Issue by rugk** [mozilla/srihash.org#154]
https://pageshot.net/BqfbQfLoOuvXP7YF/www.srihash.org

![sri](https://pageshot.net/images/055162b1-34d7-4f81-b275-9c3e37718c8b.png)

**Comment by fmarier** [comment]
You don't need to add CORS headers if the resource is on the same origin as the webpage you're including it from. You only need CORS headers if it's a third-party request.

**Comment by rugk** [comment]
That's right, but why does your test fail in this case?

**Comment by fmarier** [comment]
Because SRI Hash doesn't check for same-origin (we don't know the origin of the website which wants to include that resource) so we always look for CORS.

**Comment by rugk** [comment]
Okay, thanks for your information.
