### ISSUE TITLE
Google Fonts fails to hash

### ISSUE THREAD

**Issue by willmedtrainingsolutionscom** [mozilla/srihash.org#158]
This is the attempted URL:

 > https://fonts.googleapis.com/css?family=Open+Sans:400,600,300,700,800

It produces the error message:

    

When run here:

 > https://www.srihash.org/

**Comment by fmarier** [comment]
That's odd. The content type does appear to be set correctly on the server side:

```
$ curl --head 'https://fonts.googleapis.com/css?family=Open+Sans:400,600,300,700,800'
HTTP/1.1 200 OK
Content-Type: text/css; charset=utf-8
```

and `text/css` is what [we're looking for in the code](https://github.com/mozilla/srihash.org/blob/520c72b4c986dba687b86fa7f6f4a44d6b6aabc4/lib/resourceTypes.json#L21).

**Comment by mozfreddyb** [comment]
Maybe this got broken in sri-toolbox?
https://github.com/neftaly/npm-sri-toolbox/commit/2523cd7253c0098ebaaf5b9a40a469ab33095fb2

**Comment by fmarier** [comment]
Ah indeed, it's @jonathanKingston 's fault :)

I guess that commit should be reverted and we should release a new version of sri-toolbox?

**Comment by jonathanKingston** [comment]
Probably not reverted as it's not like SRI supports outputting content type
either. Let me debug and fix.

**Comment by jonathanKingston** [comment]
So SRI toolbox was actually just returning `""` for the content as it wasn't being passed one which made all this code work. However I don't think the check worked for when being given an invalid content type either.

Either way the right thing was to switch this to checking the response content-type headers which we were not doing.
