### ISSUE TITLE
Replace jshint and jscs with ESLint

### ISSUE THREAD

**Issue by XhmikosR** [mozilla/srihash.org#163]
I could make the switch as long as there's a config we can use. Is there a Mozilla ESLint config?

**Comment by XhmikosR** [comment]
@fmarier: is there any existent ESLint config Mozilla is using so that we don't reinvent the wheel?

**Comment by fmarier** [comment]
https://searchfox.org/mozilla-central/source/.eslintrc.js points to https://searchfox.org/mozilla-central/source/tools/lint/eslint/eslint-plugin-mozilla/lib/configs/recommended.js

**Comment by XhmikosR** [comment]
I'm not sure these even make sense for this repo... Either way we can change it later. Plus this PR depends on my previous PRs.
