### ISSUE TITLE
Allow easy output selection/copy

### ISSUE THREAD

**Issue by chocolatkey** [mozilla/srihash.org#188]
It would be nice if when the html tag is generated
![image](https://user-images.githubusercontent.com/13407784/39277830-ae5de6d6-48a4-11e8-896e-e4ed1fd53a60.png)
an option is provided to easily select the code. This could be in form of either:

1. Click on the code and the entire tag is highlighted.
2. A "copy" button that copies the code to the clipboard.

If necessary I'm willing to write a PR

**Comment by XhmikosR** [comment]
@fmarier: without a little JS I'm not sure if this is possible.

And if we add it, which I think we should, I'd reconsider #121; less requests, cleaner way IMO.

**Comment by mozfreddyb** [comment]
Closing WONTFIX. I'd argue that tripe-clicking the text might be good enough. We've already decided we don't need the website to run any kind of JavaScript in #121.

**Comment by XhmikosR** [comment]
IMO this is a very useful feature. And #121 too. I don't see the no-JS approach as good. We can still allow just our origin in the CSP.

It's not like we are in a contest to achieve something without client-side JS :P

**Comment by mozfreddyb** [comment]
> It's not like we are in a contest to achieve something without client-side JS :P

Are we not? ;D

**Comment by XhmikosR** [comment]
I'm definitely not in such contest when it clearly improves the UE.
