### ISSUE TITLE
Expired SSL Certificate

### ISSUE THREAD

**Issue by iSWORD** [mozilla/srihash.org#203]
The SSL certificate for https://www.srihash.org/ expired 14 minutes ago, please renew it :)

**Comment by fmarier** [comment]
Thanks for the notice, I just filed https://bugzilla.mozilla.org/show_bug.cgi?id=1503340 for this.

Not sure why it's not being monitored...

**Comment by fmarier** [comment]
No need to apologize, you did the right thing!

**Comment by fmarier** [comment]
And it's back. Now using a Let's Encrypt certificate using Heroku's built-in functionality. Monitoring and renewal should all be taken care of now.
