### ISSUE TITLE
Information: Decentraleyes plugin has different hashes for some CDN resources

### ISSUE THREAD

**Issue by Chaz6** [mozilla/srihash.org#205]
This is not a bug but information that hopefully helps other people.

I discovered after adding a SRI to one of my web pages that it stopped working. It turns out that the scripts included in the Chrome/Firefox Decentraleyes plugin do not match the hash of the actual script from the CDN. This plugin is designed to prevent big CDN's from tracking you by instead supplying a local copy.

Example: https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.js

```Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.js' with computed SHA-256 integrity 'h0cGsrExGgcZtSZ/fRz4AwV+Nn6Urh/3v3jFRQ0w9dQ='. The resource has been blocked.```

Corresponding bug report: https://git.synz.io/Synzvato/decentraleyes/issues/331

**Comment by MatthewHerbst** [comment]
This lib generates sha-384 hashes is the issue. The extension should probably check for 256/384/512 at minimum

**Comment by mozfreddyb** [comment]
I don't think this is an issue with srihash.org, and I'd rather not pollute this repo with issues that are best tracked and discussed in the support forum of the software that's actually affected.
