### ISSUE TITLE
Add canonical `<link>` element

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/srihash.org#209]
This website is available under 
* srihash.org
* www.srihash.org
* srihash.herokuapp.com

One could add a [canonical link element](https://en.wikipedia.org/wiki/Canonical_link_element) to clearly define which is canonical.

**Comment by Anubhavshakya** [comment]
I want to work on this bug.

**Comment by mozfreddyb** [comment]
@Anubhavshakya Looking forward to your pull request. I think we consider the full domain `www.srihash.org` the canonical name.

Do you need anything else?

**Comment by Anubhavshakya** [comment]
@mozfreddyb  Please Check #241
