### ISSUE TITLE
Free tests from remote dependencies

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/srihash.org#211]
Tests for `generateElement` #11  require remote resources. This bears the risk of instability due to those resources changing.

Would be nice if we found another way. Maybe at least there's something in [web platform tests](http://w3c-test.org/subresource-integrity/subresource-integrity.sub.html) instead?

I'd trust that a bit more :)

**Comment by XhmikosR** [comment]
There are more tests that require 3rd-party CDNs just FYI.
