### ISSUE TITLE
Replace `url.parse` with `url.URL` constructor

### ISSUE THREAD

**Issue by XhmikosR** [mozilla/srihash.org#215]
This has been deprecated in Node.js 11.

**Comment by XhmikosR** [comment]
I looked into this, but it seems the new API has issues with relative URLs. We need to pass a base option.

Which means `/foobar` throws an error with the new API. And we certainly use this.

**Comment by mozfreddyb** [comment]
Yeah, but seems doable.

**Comment by XhmikosR** [comment]
Be my guest :)
