### ISSUE TITLE
Serve CORS headers

### ISSUE THREAD

**Issue by neftaly** [mozilla/srihash.org#22]
Serve wildcard CORS headers from hapi -- particularly the "generate" route.

**Comment by fmarier** [comment]
What are we trying to get from this?

If we were to let developers use our backend from their front-ends, then we'd have to ensure that our service has a decent SLA. This is a lot of work :)

**Comment by neftaly** [comment]
I'd like to experiment with bookmarklets at some point. It would have also been useful while I was finishing up the frontend, though I ended up just using a static JSON file :)
