### ISSUE TITLE
Some Things to Fix on Site

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [mozilla/srihash.org#226]
https://srihash.org/ shows srihash.org’s server IP address could not be found.

while https://www.srihash.org/ works fine.

also 

Failed to find a valid digest in the 'integrity' attribute for resource 'https://www.srihash.org/badge/must-fail.css' with computed SHA-256 integrity 'VSi40+PeaTvPZpOaTbxRDamyWd0wl9aNjHqbuvX2TQ0='. The resource has been blocked.

**Comment by mozfreddyb** [comment]
> https://srihash.org/ shows srihash.org’s server IP address could not be found.
> while https://www.srihash.org/ works fine.
Both work fine for me?

> Failed to find a valid digest in the 'integrity' attribute for resource 'https://www.srihash.org/badge/must-fail.css' with computed SHA-256 integrity 'VSi40+PeaTvPZpOaTbxRDamyWd0wl9aNjHqbuvX2TQ0='. The resource has been blocked.

That's the SRI test badge. We try to load a "SRI is not supported" badge with an incorrect SHA-256 digest in the `integrity` attribute. If it loads, we know the browser does not support SRI. Try visiting the website with a non-compliant browser (older version, netsurf, etc) to see the difference.
