### ISSUE TITLE
Enable branch protection for master

### ISSUE THREAD

**Issue by XhmikosR** [mozilla/srihash.org#234]
Enable `Require status checks to pass before merging`:

* make sure Travis CI passes
* make sure the branches are up to date before merging

Enable `Include administrators`

Maybe even enable require code reviews too? But this can slow down things if there isn't someone available to review apart from the person who opened the PR.

**Comment by mozfreddyb** [comment]
master is now a protected branch. I'm not requiring code review, as of yet

**Comment by XhmikosR** [comment]
Perfect, thanks! I'd suggest that from now on merge isn't used. Either squash or rebase. You can disable it in the repo settings if you want.
