### ISSUE TITLE
Use CSP

### ISSUE THREAD

**Issue by fmarier** [mozilla/srihash.org#24]
We should enforce a CSP policy on this site.

[hood](https://www.npmjs.com/package/hood) might be a good module for that, it's what Firefox Accounts uses.

**Comment by neftaly** [comment]
As an aside, has there been any discussion on adding a "must-SRI" keyword to CSP?

**Comment by fmarier** [comment]
> As an aside, has there been any discussion on adding a "must-SRI" keyword to CSP?

No, but that's an interesting idea. You could suggest that for CSP3 on the [webappsec list](https://lists.w3.org/Archives/Public/public-webappsec/).

**Comment by fmarier** [comment]
I've just added a manual CSP policy to the Apache config:

    Content-Security-Policy: default-src 'none'; style-src 'self'; font-src 'self' ; frame-src 'self'

**Comment by neftaly** [comment]
Just curious, are you proxying through Apache or something? Is it for caching/naxsi?

**Comment by fmarier** [comment]
Yeah, proxying through Apache because i'm serving a bunch of other stuff on that box on ports 80 and 443.

**Comment by neftaly** [comment]
Ok. I can set it up on Heroku/Openshift/etc some time, if you'd like.

**Comment by fmarier** [comment]
I'm hoping to find a place to put it within Mozilla, but I haven't asked around yet.

**Comment by fmarier** [comment]
Now that we are looking at being hosted on Heroku, we need to add this in Node.js land.

I will make use of [hood](https://www.npmjs.com/package/hood) by @seanmonstar.

**Comment by fmarier** [comment]
Actually, hood doesn't work with hapi. Instead, we should look into:

- http://hapijs.com/api#serverrouteoptions
- https://github.com/nlf/blankie

**Comment by fmarier** [comment]
Fixed in #77.
