### ISSUE TITLE
Redirected URLs are not being followed

### ISSUE THREAD

**Issue by abhinavsagar** [mozilla/srihash.org#242]
`Error: fetching the resource returned a 301 error code.`
This error pops out while clicking the hash button of any url.

**Comment by mozfreddyb** [comment]
Can you please summarize this in simple steps for me to verify?

**Comment by XhmikosR** [comment]
Actually this is a bug I think.

Redirects aren't being followed. Test with `https://gitcdn.xyz/repo/mozilla/srihash.org/master/index.js`

https://github.com/mozilla/srihash.org/blob/e6a30b7403defe47af01a86e03a83c11b8a73786/lib/processResource.js#L19-L24

**Comment by mozfreddyb** [comment]
Having thought about this some more, I would most preferably fix this by emulating browser behavior, e.g, something that implements [`fetch`](https://fetch.spec.whatwg.org/).

https://www.npmjs.com/package/node-fetch seems interesting

Though, we want different error to be more verbose. For security reasons, `fetch()` will raise a network error for missing CORS headers.

What do others think?

**Comment by XhmikosR** [comment]
I think using node-fetch seems like a clean solution than us reinventing the wheel and not covering everything.

For now #286 goes the manual way. Not sure if we should merge until someone implements the node-fetch solution.
