### ISSUE TITLE
intermittent failures for root domain due to incorrect DNS settings 

### ISSUE THREAD

**Issue by wilimayze** [mozilla/srihash.org#243]
People cannot access your website using @ (non-www). https://srihash.org/ does not work and sites such as hacks.mozilla.org use it. You have no contact on the page either, which is why I am filing the issue here.

**Comment by mozfreddyb** [comment]
Thank you very much for filing the bug @wilimayze. 
This seems to be a DNS failure. I have reopened https://bugzilla.mozilla.org/show_bug.cgi?id=1530297

I shall find out if there's some monitoring alerts I can set up so I get to see these things earlier

**Comment by XhmikosR** [comment]
Maybe something like Server Density?

**Comment by mozfreddyb** [comment]
I don't think it makes sense to add monitoring until the DNS problem is resolved.
It seems that [we require a tiny spec violation to point the root domain](https://devcenter.heroku.com/articles/custom-domains#add-a-custom-root-domain) to heroku.
DNS is hosted by akamai, which does not allow ALIAS/CNAME records for root domains.

So, until we have DNS working out, we will continue to have intermittent failures for the non-www domain :slightly_frowning_face:, we should look monitoring in a later issue.

There are various free DNS services, I've heard great things about freedns.afraid.org for example, but I feel slightly uncomfortable doing this ourselves :slightly_frowning_face:

**Comment by wilimayze** [comment]
Do you not have an A record for the root domain (@) that points to the IP address for your server?

**Comment by mozfreddyb** [comment]
I do. But as pointed out in the link above, Heroku does not play well with A records.

**Comment by XhmikosR** [comment]
Can't we have a second instance just for this? Also, now I'm not sure if #184 will help or not...

**Comment by mozfreddyb** [comment]
Second instance of what? The problem is at the DNS level..

**Comment by XhmikosR** [comment]
Second app instance, but yeah, it doesn't solve the issue if it's on the DNS level.

**Comment by mozfreddyb** [comment]
OK, this just got worse. Due to the DNS failure, we couldn't renew the certificate. I'm asking internally to find someone who can host DNS for me. :frowning:

**Comment by mozfreddyb** [comment]
I finally came to a conclusion, that should *really* be documented somewhere.

So we went back to split hosting
`srihash.org` is hosted separately on a different server with letsencrypt + a HTTP 301 permanent redirect to `www.srihash.org`
the actual app is only at `www.srihash.org` and remains on heroku
