### ISSUE TITLE
consider moving the hashing part into the frontend

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/srihash.org#269]
Hosting this is becoming tricky.
The #204 problem is due to the way we broke split hosting.
Turns out, the non-www domain used to be hosted on Mozilla properties, which means we ended up with two servers and two certificates. The non-www hosted on Mozilla servers just redirected to www on Heroku which contained the actual application logic.

We would lose some granularity on error messages (Network Error for both non-CORS and non-available), but save a lot of computing resources.

Implementation would be along the lines of 

```js
res = await fetch("https://code.jquery.com/jquery-3.4.1.min.js")
// Response { type: "cors", url: "https://code.jquery.com/jquery-3.4.1.min.js", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers, body: ReadableStream, bodyUsed: false }
buf = await res.arrayBuffer()
// ArrayBuffer { byteLength: 88145 }
digest = await crypto.subtle.digest("SHA-384", buf);
// ArrayBuffer { byteLength: 48 }
base64String = btoa(String.fromCharCode(...new Uint8Array(digest)));
// "vk5WoKIaW/vJyUAd9n/wmopsmNhiy+L2Z+SBxGYnUkunIxVxAv/UtMOhba/xskxh"
result = 'sha-384' + base64String;
```

wdyt @XhmikosR ?

**Comment by XhmikosR** [comment]
I'm not sure I follow... Can't we just use a better DNS provider which allows us to host www and naked on Heroku?

**Comment by mozfreddyb** [comment]
I don't want to move this to my (or anyone's) private infra, and finding a better DNS provider seems to require finding someone who pays for it, which is unlikely and imho not worth the hassle. But given that this project has no other stakeholders inside of Mozilla than myself :confused: 

Going back to the split-hosting is even more costly as it would require two servers and two certs. That'd be just nonsense :smile: 

Finding infra for static web hosting could be much simpler.

**Comment by mozfreddyb** [comment]
That would also disallow us from doing content type checks and other things the server-side part is doing. Nevermind :|

I'll keep looking for a DNS solution that isn't AWS and isn't pricy :frowning:

**Comment by XhmikosR** [comment]
We can just use Cloudflare.

**Comment by mozfreddyb** [comment]
custom CNAMEs look to be only offered in the Business tier.
