### ISSUE TITLE
Separate production from development branches

### ISSUE THREAD

**Issue by XhmikosR** [mozilla/srihash.org#276]
Maybe we should have a prod branch or something, or maybe we rename master to devel and we only merge to master for production deployments.

**Comment by XhmikosR** [comment]
This is now done. The master branch is for development and the production for production releases.

We still need to set up a Heroku app for master with a subdomain so that we can preview it.

**Comment by mozfreddyb** [comment]
**Staging**: https://srihash-staging.herokuapp.com/ follows the *master* branch
**Release**: https://www.srihash.org/ will follow the *production* branch
