### ISSUE TITLE
Better errors

### ISSUE THREAD

**Issue by fmarier** [mozilla/srihash.org#3]
Instead of just returning an empty string, we should return a proper message when:
- we ran into problems fetching the resource
- the resource is not eligible for SRI protection

**Comment by adhikasp** [comment]
Is it already implemented? 95cd8da38222fbdf7ff73d96d844b25df0eb3fbf

**Comment by fmarier** [comment]
You're right, I think it's fairly well covered now. Thanks for pointing this out!
