### ISSUE TITLE
Add instructions on getting an SRI-supported browser to test with

### ISSUE THREAD

**Issue by fmarier** [mozilla/srihash.org#31]
Given the recent hash format change, neither my [initial patch](https://bugzilla.mozilla.org/show_bug.cgi?id=992096) nor the Chrome Dev channel have support for the spec.

Once it's possible to test this feature using these browsers, we should add instructions on how to do it.

**Comment by neftaly** [comment]
I would like to put a badge right on the main page, that changes depending on SRI support.

**Comment by fmarier** [comment]
I really like the badge idea.

It would be similar to these DNSSEC checking tools:

- https://www.dnssec-tools.org/
- http://test.dnssec-or-not.org/

**Comment by neftaly** [comment]
It's just a matter of ```<img src="sri_unsupported.png" integrity="sha256-delibarateFail" noncanonical-src="sri_supported.png">``` or whatever, right? Though I'd also link to a full QUnit test.

**Comment by fmarier** [comment]
Not quite because `noncanonical` has been removed from the spec and `<img>` elements are not suppoted.

Here's an idea that should work with CSP and doesn't require JS to be enabled:

1. create a  `<div>` with a fixed size
2. load a styleshet without an integrity attribute that sets the background image on the div to `success.png`
3. load a second stylesheet with a broken integrity attribute which sets the background image on the div to `fail.png`

A browser without SRI will load both stylesheets and the second one will override the first. A browser with SRI will only load the first stylesheet.

**Comment by neftaly** [comment]
Good idea. I would suggest `visibility: hidden`, and just hiding/showing the entire success/failure div (which contains an `<img>` and some "Congratulations!" text or whatever).

**Comment by fmarier** [comment]
> I would suggest visibility: hidden, and just hiding/showing the entire success/failure div

Yes, that sounds better and easier.

**Comment by fmarier** [comment]
Oops, this bug is not actually closed, only the badge part is done.

**Comment by jonathanKingston** [comment]
The browser support section might work copying the following: https://github.com/jonathanKingston/ember-cli-sri

**Comment by fmarier** [comment]
So we can now add links to:

- [Chrome](https://www.google.com/chrome/browser/desktop/)
- [Firefox](https://www.mozilla.org/en-US/firefox/channel/#developer)

Ideally randomizing the order of them in the template :)
