### ISSUE TITLE
Be opinionated about content-type

### ISSUE THREAD

**Issue by neftaly** [mozilla/srihash.org#32]
Show a warning whenever a non-canonical/uncommon/deprecated content-type header is served. 

This will improve SRI portability between CDNs (for example, two CDNs serving the same file with both an application/javascript and application/x-javascript header). It would also make assumptions about a default content-type on the SRI build task easier. 

Going further, we should consider picking a single preferred content-type for each file format.

**Comment by fmarier** [comment]
We can't pick a preferred content-type, it has to be whatever the CDN is serving otherwise the load will be blocked.

Showing a warning about a weird content-type to users is not going to be very useful because they can't fix it in most cases.

I think what we can do (and that might be what you had in mind) is stop defaulting to JS and return an error if the content-type is one that's not in our list of known content-types

**Comment by neftaly** [comment]
By "preferred" content-type, I mean the "one true content-type" for each file type, that we would personally prefer servers to be hosting with. This would also be the default content-type for stuff generated by the Grunt plugin. This isn't relevant to `guessElementType`.

While CDNs probably won't be using srihash.org to generate integrity attributes, users may be encouraged to advocate for their CDNs to *only* use `application/javascript` or whatever. It'll also provide a warning that things may break if the CDN decides to change from an obsoleted content-type header to a more common one (the time to fix it is now). 

It might be worth mentioning content-types to CDNs when we reach out to them regarding SRI. We could also explain on the main page what could happen if a ct did not match (does it refuse to load? does it break planned caching?). 

I would hope that, in time, srihash.org will no longer be such a relevant tool, and would more commonly be used by people writing their own resources. In this application, they could also be assumed to have direct control over the content-type header.

I hadn't actually considered your last point, but I like it. I think I'll make the React implementation return the SRI attribute in a different visual style when an unexpected format is encountered (instead of an error).

**Comment by fmarier** [comment]
This is one of those things that's extremely hard to fix later because you end up "breaking the web". Also, there's not really any incentives for a CDN to move from `text/x-javascript` to `application/javascript`.

**Comment by neftaly** [comment]
Closing this issue, as it is more-or-less covered in #42.
