### ISSUE TITLE
Add dependabot

### ISSUE THREAD

**Issue by XhmikosR** [mozilla/srihash.org#320]
@mozfreddyb I think we should add dependabot to the repo. We just need to configure it properly to update both package.json and the lock file

**Comment by mozfreddyb** [comment]
I agree :)

**Comment by XhmikosR** [comment]
@mozfreddyb let me know when you add it so that I look into configuring it.

**Comment by mozfreddyb** [comment]
Took me down a tiny rabbit hole, but it's listed in the Integrations panel. Looking forward to your configuration ;)

**Comment by XhmikosR** [comment]
Are you sure it's set up properly? For example eslint has eslint 6.5.1 released but I don't see any PRs.

**Comment by mozfreddyb** [comment]
Sorry. It now is. See #324 #325 etc.

Given that we have our main branch point to a staging server, I'm toying with the idea of letting dependabot automatically fill PRs *and merge them*, if all tests pass. Would greatly help us testing and I see little risk.

What do you think?

**Comment by XhmikosR** [comment]
I'd say no, because we don't build PR previews.

**Comment by mozfreddyb** [comment]
Yup, but if we auto-merge, we would get to look at it on staging.

**Comment by XhmikosR** [comment]
I don't like this approach. The idea is to catch errors before something lands.

**Comment by XhmikosR** [comment]
This is done for some time now
