### ISSUE TITLE
Add social related tags

### ISSUE THREAD

**Issue by XhmikosR** [mozilla/srihash.org#334]

**Comment by mozfreddyb** [comment]
This could be a good first bug. What we want are meta tags like this:


```html
  <meta property="og:site_name" content="..."/>
  <meta property="og:type" content="website"/>
  <meta name="twitter:card" content="summary"/>
  <meta name="description" content="..." />
  <meta property="og:title" content="...."/>
  <meta property="og:url" content="...."/>
  <meta name="twitter:title" content="..." />
  <meta name="twitter:description" content="..." />
```

**Comment by vanshaj234** [comment]
I would like to do this.

**Comment by vanshajtyagi** [comment]
i would like to work on this issue.
![Capture](https://user-images.githubusercontent.com/45164555/86026488-1cffdd80-ba4d-11ea-8dc5-bad00baab3bd.PNG)

**Comment by mozfreddyb** [comment]
yup. please issue a pull request

**Comment by vanshaj234** [comment]
#1

**Comment by vanshaj234** [comment]
index.html

**Comment by vanshajtyagi** [comment]
#446 
I have made a pull request .please tell me what else do u want in, as this was my first pull request and I got little confused while making it

**Comment by mozfreddyb** [comment]
#446 and #447 close this. Thank you @vanshaj234
