### ISSUE TITLE
Fix the styling of the "results" iframe

### ISSUE THREAD

**Issue by fmarier** [mozilla/srihash.org#36]
Currently the "results" iframe is pretty hard to read:

![sri-hash-unreadable](https://cloud.githubusercontent.com/assets/167821/6317014/5d01b21a-baa2-11e4-8b0f-c5711df0b94b.png)

I suggest:

* using either a light color for the text, or using a light background colour
* making the text wrap so that scrolling is not necessary

**Comment by neftaly** [comment]
http://neftaly.com/srihash.org-client/
https://github.com/neftaly/srihash.org-client
:)

I'll update it now that we've got everything else going (keeping it server-side only for now).

**Comment by fmarier** [comment]
Yeah, I'm thinking we should do a quick fix for now, the real fix will be the awesome new front-end you're cooking up :)
