### ISSUE TITLE
"Content-type" header is passed directly into result

### ISSUE THREAD

**Issue by neftaly** [mozilla/srihash.org#38]
We need to parse the content-type header before generating the SRI attribute.

```
request.result = {
    'content-type': 'text/javascript; charset=UTF-8'
   ...
}
sri.generateHash (request.result);
//=> "<script src="file.js" integrity="type:text/javascript; charset=UTF-8 sha256-..."></script>"
```

This is a security issue; both XSS and the ability to spoof hashes. 

```
request.result = {
    'content-type': 'text/javascript sha512-fAkEhAsH'
   ...
}
sri.generateHash (request.result);
//=> "<script src="file.js" integrity="type:text/javascript sha512-fAkEhAsH sha256-rEaLhAsH"></script>"
```

I'm mad at myself for not noticing this earlier.

**Comment by neftaly** [comment]
To see an example of this, try hashing just "https://code.jquery.com/"

**Comment by fmarier** [comment]
I guess we need to:

1. split the string on semicolons (`;`)
2. only use the first string returned in the first step and discard all others
3. split the string on slash (`/`)
4. ensure that both sides match `[A-Za-z0-9_.-]+` (or better yet, use a built-in validator in node or hapi if they exist)

**Comment by neftaly** [comment]
I'll let you handle this, if you don't mind.
NB this could potentially lead to a security issue (spoofing hashes).

**Comment by neftaly** [comment]
I would force string termination after *anything* that looked like a delimiter to the browser SRI interpreter.

**Comment by fmarier** [comment]
Yeah, at the very least, we should have a blacklist to detect spaces and closing quotes, but whitelist-based approaches (only look at what you expect) are generally better.

**Comment by neftaly** [comment]
Just a note, I plan to audit every I/O in the XHR handler, to check that dodgy values can't be injected elsewhere.

**Comment by neftaly** [comment]
Regarding the spec, is there a reason "type" is included at all? Now that it's not a per-hash ni-URI parameter, I don't see any actual use for it that isn't already covered by the HTML `type` attribute.

**Comment by fmarier** [comment]
I'm not an expert on the HTML `type` attribute but I believe it's for a different purpose. I think it's for telling the browser "treat this resource as this content type regardless of what the server says it is". SRI on the other hand says "block this resource unless it comes with the right content-type header from the server".

**Comment by neftaly** [comment]
I can't find the issue, but I remember reading somewhere that the reason for content-type matching was to prevent an `application/javascript` file with some hidden VBS being parsed as `application/vbscript` (or something). Wouldn't this do the same thing, whilst simplifying the spec, and removing any ambiguity?

I know this is the wrong place to ask, but w3c/webappsec is imposing, and I'm not familiar with the etiquette :)

**Comment by neftaly** [comment]
Nevermind, I see the issue now! I'll explain a little further in a new srihash.org issue.
