### ISSUE TITLE
Handle presentation for unknown file formats differently

### ISSUE THREAD

**Issue by neftaly** [mozilla/srihash.org#42]
At the moment we currently fallback to `js` for unrecognized content-types, and output a `<script>` tag:
```html
<script src="hello.pdf" integrity="type:application/pdf sha256-ZZZZ"></script>
```

I propose that for unrecognized content-types we generate only the attribute itself:
 ```
integrity="type:application/pdf sha256-ZZZZ"
```

In the future, we can differentiate the output even further:
> Please insert the following attribute into your element:
> `integrity="type:application/pdf sha256-ZZZZ"`

**Comment by neftaly** [comment]
To achieve this, I propose that `guessElementType` should output `null` for an unrecognized content-type. `undefined` is not suitable, as the result will be expected to be sent over the wire in JSON format.

**Comment by fmarier** [comment]
I'd rather not generate attributes for things that are not supported anywhere. Since this is a webapp, we can update it easily and keep it in sync with the spec (and/or implementations).

**Comment by neftaly** [comment]
Ok. So only CSS and JS is supported in the current version?
We can just forward the result (`null`) to the view layer, and have it generate an error message.

Can we still show the output below the error message? Failing to do so would present an issue for (otherwise valid) content-types like `application/dart`, `text/jsx`, and whatever else the user is doing with a custom `<script>` interpreter.

**Comment by fmarier** [comment]
Well currently, it's not a problem because we default to JS.

**Comment by neftaly** [comment]
Oh, that's why I used `application/pdf` in the first example. There is currently no mechanism to show an error or warn the user in any way about it.

**Comment by fmarier** [comment]
I think we could still default to JS and generate a proper script element, but have a warning that says something like "Are you sure that's the right content-type for your script?"

**Comment by neftaly** [comment]
Sure. I would still like to implement that by returning `null` from `guessContentType`, OK?

**Comment by fmarier** [comment]
Sounds goods to me.
