### ISSUE TITLE
Generated Script Resource Invalid

### ISSUE THREAD

**Issue by lbussy** [mozilla/srihash.org#434]
When a CDN link is input on the https://www.srihash.org/ website, the generated HTML is invalid.

Input:
``` html
https://cdnjs.cloudflare.com/ajax/libs/hyperform/0.12.0/hyperform.min.js
```

Output:
``` html
<script src="https://cdnjs.cloudflare.com/ajax/libs/hyperform/0.12.0/hyperform.min.js" integrity="sha384-U7Og6omFJeTauQSJ6GPbHy/LPR9+a7zMZGbZZXZiK8Td2O0MSBEi8wS01IGi5+Zy" crossorigin="anonymous></script>
```

The `crossorigin` attribute is lacking a closing quote wrapping `"anonymous"`.

**Comment by mozfreddyb** [comment]
Currently going through a bit of a rewrite. nice catch @lbussy.
