### ISSUE TITLE
How verify a SRI for a file

### ISSUE THREAD

**Issue by ZerooCool** [mozilla/srihash.org#443]
How verify a SRI for a file

**Comment by mozfreddyb** [comment]
srihash.org has a section about that:

> **How can I generate Integrity hashes?**
> 
> Use the generator above or the following shell command:
> openssl dgst -sha384 -binary FILENAME.js | openssl base64 -A 

Does that work for you? If not, is this a feature request for srihash.org to support file uploads?

**Comment by ZerooCool** [comment]
Yes for generate a hash, but, i search how i can verify a hash, with command line.

**Comment by mozfreddyb** [comment]
You might be looking for something like https://github.com/zkat/srisum-rs/ then.

**Comment by ZerooCool** [comment]
Perfect for me, I haven't tested yet but it seems perfectly suited. Thank you so much. I will add this link in my notes and mention it for the Privatebin project.
