### ISSUE TITLE
Add (static) syntax highlighting to the snippet

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/srihash.org#454]
Would be nice if the generated snippet had colors. They could be baked into the way srihash.org and there would not be a need to generate them on the fly.

This requires the abandoning current text-only approach and making sure not to introduce a cross-site scripting vulnerability.
E.g., we currently do
```
    if (response.status === 200) {
      const text = await response.text();
      const hashBuffer = await hashText(text); // Array Buffer
      const base64string = btoa(
        String.fromCharCode(...new Uint8Array(hashBuffer))
      );
      const integrityMetadata = `sha384-${base64string}`;
      const scriptEl = `<script src="${encodeURI(
        url
      )}" integrity="${integrityMetadata}" crossorigin="anonymous"></script>`;

      resultDiv.innerText = scriptEl;
```

instead, we'd have to end up in restultDiv.innerHTML, which is a bit dangerous.

**Comment by Yogendra0Sharma** [comment]
@mozfreddyb can I work on this issue?
