### ISSUE TITLE
at tag is not supported

### ISSUE THREAD

**Issue by randomsymbols** [mozilla/srihash.org#474]
This will **not** work 
https://cdn.jsdelivr.net/npm/daterangepicker**@3.1.0**/daterangepicker.css

This **will** work 
https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css

**Comment by mozfreddyb** [comment]
I'm not sure I understand what you are complaining about.
Both URLs worked for me, but the web page produced a script tag, not a style tag.

Is that what you observed?

**Comment by mozfreddyb** [comment]
Please reply if you're still seeing the issue. At this stage, I'm not sure what you were reporting in the first place.
