### ISSUE TITLE
Google Fonts sends different responses depending on browser. Using srihash.org will only provide one of many required hashes.

### ISSUE THREAD

**Issue by MumblingFumbler** [mozilla/srihash.org#514]
SRI Hash Input:
    https://fonts.googleapis.com/icon?family=Material+Icons
SRI Hash Output:
    \<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" integrity="sha384- zfmep/8lfJ4cVW8HCW1SWfWf0ckqJhJDO5kJ2udXM/imt7aX9neyBDFFyuL1TT50" crossorigin="anonymous"\>

Browser(s) (Chrome and Firefox) error
The hash in the 'integrity' attribute doesn't match the received payload.

**Comment by kota-yata** [comment]
Your hash output does not match the URL. 
The actual hash384 output for ```https://fonts.googleapis.com/icon?family=Material+Icons``` is ```sha384-r4ArzcycohCKpd5lRaMM1i3qmqqCo7BsUvmnhusfNZ5LXOGHyZR8j+TURxWIGUO/```

**Comment by MumblingFumbler** [comment]
I used this website: https://www.srihash.org/ Is this the wrong site?
I used this URL:  https://fonts.googleapis.com/icon?family=Material+Icons
I selected 'SHA-384' from the pulldown to the right of the URL
I clicked on 'Hash!'
I copied the following output:
\<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" integrity="sha384-zfmep/8lfJ4cVW8HCW1SWfWf0ckqJhJDO5kJ2udXM/imt7aX9neyBDFFyuL1TT50" crossorigin="anonymous"\>
I got the following error:
Browser(s) (Chrome and Firefox) error
The hash in the 'integrity' attribute doesn't match the received payload.
What could I do differently on the site to get the hash that you came up with?
Even when I paste in your hash from above, I get the same error

**Comment by kota-yata** [comment]
I cannot reproduce your bug on my computer. Could you record your screen during the operation above please?

**Comment by MumblingFumbler** [comment]
![SRI Hash Generator](https://user-images.githubusercontent.com/52546298/142507746-29664c96-b3a0-4fe3-83b4-9147209af506.JPG)
Browser Version:
![Firefox Version](https://user-images.githubusercontent.com/52546298/142508050-8cdeb6b7-539e-429d-aa83-bbadd6f6d811.JPG)

Hope this helps

**Comment by MumblingFumbler** [comment]
Here is a description of the problem from someone else:
https://stackoverflow.com/questions/44043585/google-chrome-sri-hash
sounds like the hash is browser dependent. If I acquire the has on Firefox,
and display using Chrome, it doesn't work? I'll test...
Having to use a different hash depending on the browser would be unfortunate.

**Comment by MumblingFumbler** [comment]
Yeesh!!! The hash generated is browser dependent. If I generate on Firefox and display on Chrome, I get an error.
and vice-versa. If I display on the same version as generated, it works. Bad news!

**Comment by kota-yata** [comment]
Well...Google Fonts seems to have some problems...
I think we could do nothing with this problem, since the hash value should change if the content of the file has changed.

**Comment by kota-yata** [comment]
One possible way is generating multiple hash value for different user agent as [this comment](https://github.com/google/fonts/issues/473#issuecomment-451739625). I will try this solution.

**Comment by mozfreddyb** [comment]
To summarize: Google Fonts is serving a different file depending on the browser being used. Naturally, srihash.org can only detect the resource that the _current_ browser is seeing and can not ensure the server will always serve the same response.


I could imagine turning this issue into a work item detect about popular CDNs that serve browser-dependent payloads on srihash.org and emit a tiny warning/info box when people use it for e.g., google fonts. Would anyone of the folks in there be interested in figuring out and implementing such a feature?

**Comment by kota-yata** [comment]
I'm working on it.

**Comment by mozfreddyb** [comment]
#518 :)
