### ISSUE TITLE
Lint the stylesheets

### ISSUE THREAD

**Issue by fmarier** [mozilla/srihash.org#52]
We should have a linter for our CSS files.

Currently one of them has a problem:

> Error in parsing value for 'width'.  Declaration dropped. badge.css:41

**Comment by fmarier** [comment]
The actual typo is fixed in #80, but my point still stands: we should lint our stuff :)

**Comment by XhmikosR** [comment]
@mozfreddyb @fmarier: what linter do you have in mind? CSS Lint would have caught this as far as I can tell.

**Comment by mozfreddyb** [comment]
:+1 for csslint. @fmarier can you make the call?

**Comment by fmarier** [comment]
Anything that we can integrate easily into our regression tests sounds good to me :)
