### ISSUE TITLE
srihash is computing incorrect hashes

### ISSUE THREAD

**Issue by dotysan** [mozilla/srihash.org#524]
What am I doing wrong here?

srihash.org generates `<script src="https://cdnjs.cloudflare.com/ajax/libs/jssor-slider/28.0.0/jssor.slider.min.js" integrity="sha256-yznRSx6ayLdKMNUSjq3DkyFJh9gIIF1xi0iZYyoDtXk=" crossorigin="anonymous"></script>`

but  `curl -s https://cdnjs.cloudflare.com/ajax/libs/jssor-slider/28.0.0/jssor.slider.min.js |openssl dgst -sha256 -binary - |openssl base64 -A` outputs:
`/oxe+/Z/w8SQf2vru/KlmaAi7ULMr49OOYPYXD89D/A=`

**Comment by freddyb** [comment]
I get an even different script element from the one you are receiving, `<script src="https://cdnjs.cloudflare.com/ajax/libs/jssor-slider/28.0.0/jssor.slider.min.js" integrity="sha512-Ul0u9T+Vm41eeJU8FafRBc5WVRqH+eeeb1/JtDGhmKsyfi8rqWxNa5ojMb9XzHWBBf7YO2eGT4qoCn1xCjg5LQ==" crossorigin="anonymous"></script>`.

Maybe cloudflare is sending a different response depending on user agent? It smells a bit like #514 / #518.

Can you find out?

**Comment by dotysan** [comment]
@freddyb My test case was with sha256, and you used sha512.. When I test with sha512 I get the same (but apparently bogus) hash as you. However, openssl still disagrees: `curl -s https://cdnjs.cloudflare.com/ajax/libs/jssor-slider/28.0.0/jssor.slider.min.js |openssl dgst -sha512 -binary - |openssl base64 -A`
`hIV4+MQS3ysAwIMfFP0KMFJXp72W2/+gF595ZWxDjEQFh7UHQ4bq2lAwum2kkr2E36lZvax+Y8tuAQez2Lga7w==`

**Comment by dotysan** [comment]
I fiddled with various UAs in `curl` and always got the same hash from cdnjs.cloudflare.com. So don't think this is directly related to #514/#518.

**Comment by mozfreddyb** [comment]
OK, sorry for not getting back to this. Whatever we're doing is clearly a bug here. Thanks a lot for filing it! I'll dig a bit deeper to see why we're coming up with a wrong hash.

**Comment by mozfreddyb** [comment]
I've traced this along with the DevTools debugger and it seems the bytes going into the digest method must be already wrong. Ugh?! I could confirm the computed digest is incorrect for all digest algorithms and regardless of the browser being used. This is definitely a bug in our code.

**Comment by dotysan** [comment]
Something amuck with jssor.slider.min.js as it contains some binary goop.

`curl -s https://cdnjs.cloudflare.com/ajax/libs/jssor-slider/28.0.0/jssor.slider.min.js |hexdump -C |head`
```
00000000  ef bb bf 2f 2a 21 0a 4a  73 73 6f 72 20 53 6c 69  |.../*!.Jssor Sli|
00000010  64 65 72 20 28 4d 49 54  20 6c 69 63 65 6e 73 65  |der (MIT license|
00000020  29 0a 2a 2f 0a 2f 2a 20  65 73 6c 69 6e 74 2d 64  |).*/./* eslint-d|
00000030  69 73 61 62 6c 65 20 2a  2f 0a 21 66 75 6e 63 74  |isable */.!funct|
00000040  69 6f 6e 28 69 2c 68 2c  6d 2c 65 2c 64 2c 6b 2c  |ion(i,h,m,e,d,k,|
00000050  66 29 7b 6e 65 77 28 66  75 6e 63 74 69 6f 6e 28  |f){new(function(|
00000060  29 7b 7d 29 3b 76 61 72  20 63 3d 7b 75 3a 6d 2e  |){});var c={u:m.|
00000070  50 49 2c 6c 3a 6d 2e 6d  61 78 2c 6a 3a 6d 2e 6d  |PI,l:m.max,j:m.m|
00000080  69 6e 2c 48 3a 6d 2e 63  65 69 6c 2c 47 3a 6d 2e  |in,H:m.ceil,G:m.|
00000090  66 6c 6f 6f 72 2c 50 3a  6d 2e 61 62 73 2c 67 62  |floor,P:m.abs,gb|
```

If you skip over the 3 leading mystery bytes `ef bb bf`, you get the same hash generated!!

`curl -s https://cdnjs.cloudflare.com/ajax/libs/jssor-slider/28.0.0/jssor.slider.min.js |dd skip=3 bs=1 status=none |openssl dgst -sha256 -binary - |openssl base64 -A ; echo`
`yznRSx6ayLdKMNUSjq3DkyFJh9gIIF1xi0iZYyoDtXk=`

It appears the root cause is [BOM](https://en.wikipedia.org/wiki/Byte_order_mark).

**Comment by dotysan** [comment]
I'm not familiar with your code. But this looks promising: https://eslint.org/docs/rules/unicode-bom

**Comment by mozfreddyb** [comment]
A very helpful clue :) thanks a lot for filing and investigating with me @dotysan!
