### ISSUE TITLE
Explain further the crossorigin attribute usage

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/srihash.org#69]
So in the ember addon I have explained a little further about the `crossorigin` attribute usage:
https://github.com/jonathanKingston/ember-cli-sri

Something like:
## Crossorigin attribute

When the request doesn't match Same Origin Policy the [crossorigin attribute](https://html.spec.whatwg.org/multipage/infrastructure.html#cors-settings-attribute) **MUST** be present for the integrity of the file to be checked.
With an integrity set on an external origin and a missing crossorigin then the browser will choose to 'fail-open' which means it will load the resource as if the integrity attribute was not set.

Values:
- **anonymous** - A cross-origin request (i.e., with Origin: HTTP header) is performed. But no credential is sent (i.e., no cookie, no X.509 certificate, and no HTTP Basic authentication is sent). If the server does not give credentials to the origin site (by not setting the Access-Control-Allow-Origin: HTTP header), the resource will be tainted and its usage restricted.
- **use-credentials** - A cross-origin request (i.e., with Origin: HTTP header) performed with credential is sent (i.e., a cookie, a certificate, and HTTP Basic authentication is performed). If the server does not give credentials to the origin site (through Access-Control-Allow-Credentials: HTTP header), the resource will be tainted and its usage restricted.

**Comment by robertdudaa** [comment]
Just to get it right: there should be an explanaition further the crossorigin attribute usage, below the other q&a's..
I'd like to take up this issue.

**Comment by bbs99168** [comment]
@fmarier

**Comment by mozfreddyb** [comment]
Seems this is still up for grabs. Looking forward to seeing a pull request.
