### ISSUE TITLE
CSS file is returned as a script tag

### ISSUE THREAD

**Issue by ScottHelme** [mozilla/srihash.org#95]
If I hash the following asset the service returns a script tag for use:

https://securityheaders.azureedge.net/style-desktop.min.css?v=1.0.2

Dropping the version parameter seems to resolve the problem.

**Comment by mozfreddyb** [comment]
Hm, it also says `<!-- Warning: Unrecognized content-type. Are you sure this is the right resource? -->`

**Comment by mozfreddyb** [comment]
I'm not sure why the content-type check fails, but I just found out why the filename based fallback doesn't work, so I'll start with this one.

**Comment by mozfreddyb** [comment]
@fmarier: I couldn't figure out why this fails the content-type check, maybe you can take a look later today?
@ScottHelme: Thank you for reporting this! :)
